In [57]:
import numpy as np

Array

In [58]:
arr_1 = np.array([1,2,3])
print(arr_1)

[1 2 3]


In [59]:
arr_2 = np.array([[1,2,3],[4,5,6]])
print(arr_2)

[[1 2 3]
 [4 5 6]]


In [60]:
arr_3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr_3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


Array Attributes

In [61]:
print(arr_1.shape)
print(arr_2.shape)
print(arr_3.shape)

(3,)
(2, 3)
(1, 3, 3)


In [62]:
print(arr_1.size)
print(arr_2.size)
print(arr_3.size)

3
6
9


In [63]:
print(arr_1.ndim)
print(arr_2.ndim)
print(arr_3.ndim)

1
2
3


In [64]:
print(arr_1.dtype)
print(arr_2.dtype)
print(arr_3.dtype)

int64
int64
int64


Array Intialization Methods

In [65]:
zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [66]:
one_arr = np.ones((2,3))
print(one_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [67]:
full_arr = np.full((2,3),7)
print(full_arr)

[[7 7 7]
 [7 7 7]]


In [68]:
identity_arr = np.eye(3)
print(identity_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [69]:
empty_arr = np.empty(5)
print(empty_arr)

[4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323]


In [70]:
arange_arr = np.arange(1,10,2)
print(arange_arr)

[1 3 5 7 9]


In [71]:
linspace_arr = np.linspace(1,10,4)
print(linspace_arr)

[ 1.  4.  7. 10.]


In [72]:
random_arr = np.random.rand(3,2)
print(random_arr)

[[0.43821033 0.06867937]
 [0.86094976 0.69852375]
 [0.79986298 0.64164148]]


In [73]:
random_int_arr = np.random.randint(1,100,(3,3))
print(random_int_arr)



[[18 80 21]
 [ 8 22 66]
 [87 61 77]]


Array Indexing

In [74]:
arr_1 = np.array([1,2,3,4,5])
print(arr_1[0])
print(arr_1[4])
print(arr_1[-1])

1
5
5


In [75]:
arr_2 = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr_2[0][0])
print(arr_2[1][2])
print(arr_2[1])

1
6
[4 5 6]


In [76]:
arr_3 = np.array([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
print(arr_3[0, 2, 2])
print(arr_3[0])
print(arr_3[0, 1])

9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]


Array Slicing

In [77]:
arr_1 = np.array([1,2,3,4,5,6,7,8,9])
print(arr_1[0:7:2])
print(arr_1[::-1])
print(arr_1[::2])



[1 3 5 7]
[9 8 7 6 5 4 3 2 1]
[1 3 5 7 9]


In [78]:
arr_2 = np.array([
    [1,2,3],
    [4,5,6]
    ])
print(arr_2[:, 1])
print(arr_2[:, 0])
print(arr_2[:, 2])

[2 5]
[1 4]
[3 6]


In [79]:
arr_3 = np.array([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
print(arr_3[:, 0, :])
print(arr_3[:, :, 2])
print(arr_3[0, 0:2, 1:3])

[[1 2 3]]
[[3 6 9]]
[[2 3]
 [5 6]]


Array Reshaping

In [80]:
arr = np.array([1,2,3,4,5,6])
arr_reshape = arr.reshape(2,3)
print(arr_reshape)

[[1 2 3]
 [4 5 6]]


Array Flattening

In [81]:
print(arr_reshape.flatten())

[1 2 3 4 5 6]


Array Stacking

In [82]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])
print(np.vstack((arr_1,arr_2)))
print(np.hstack((arr_1,arr_2)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


Array Splitting

In [83]:
arr = np.array([[1,2,3], [4,5,6]])

hsplit = np.hsplit(arr,3)

for s in hsplit:
    print(s)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [84]:
vsplit = np.vsplit(arr,2)

for s in vsplit:
    print(s)

[[1 2 3]]
[[4 5 6]]


Mathematical Operations

In [85]:
arr = np.array([1,2,3,4,5])
print(arr + 10)
print(arr - 5)
print(arr * 9)
print(arr / 4)

[11 12 13 14 15]
[-4 -3 -2 -1  0]
[ 9 18 27 36 45]
[0.25 0.5  0.75 1.   1.25]


In [86]:
arr_2 = np.array([7,8,9,0])
print(np.square(arr_2))
print(np.sqrt(arr_2))

[49 64 81  0]
[2.64575131 2.82842712 3.         0.        ]


In [87]:
arr_3 = ([[1,2,3],[4,5,6]])

angles_deg = np.array([0, 30, 45, 60, 90])
angles_rad = np.deg2rad(angles_deg)

sine_values = np.sin(angles_rad)
cosine_values = np.cos(angles_rad)
tangent_values = np.tan(angles_rad)

print("Angles (deg):", angles_deg)
print("Sine:", sine_values)
print("Cosine:", cosine_values)
print("Tangent:", tangent_values)

Angles (deg): [ 0 30 45 60 90]
Sine: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


Mathematical Operations on Multidimensional Array

In [88]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

print(np.add(arr_1,arr_2))
print(np.subtract(arr_1,arr_2))
print(np.multiply(arr_1,arr_2))
print(np.divide(arr_1,arr_2))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [89]:
print(np.dot(arr_1,arr_2))

32


In [90]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


Statistical Functions

In [91]:
arr = np.array([[1,2,3],[4,5,6]])

print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.min(arr))
print(np.max(arr))

21
3.5
3.5
1.707825127659933
1
6


Array Comparison

In [92]:
arr_1 = np.array([1,5,3])
arr_2 = np.array([4,5,6])

print(arr_1 == arr_2)
print(np.array_equal(arr_1,arr_2))

[False  True False]
False


Broadcasting

In [93]:
arr_1 = np.array ([1,2,3])
arr_2 = np.array([5])
print(arr_1 + arr_2)

[6 7 8]


In [94]:
arr_3 = np.array([10,20,30])
arr_4 = np.array([[1,2,3],[4,5,6]])
print(arr_3 + arr_4)

[[11 22 33]
 [14 25 36]]


Handling With null values

In [95]:
data_1 = np.array([1 , 2 , np.nan , 4 , np.inf])
print(data_1)
print(np.isnan(data_1))

[ 1.  2. nan  4. inf]
[False False  True False False]


In [96]:
print(np.nan_to_num(data_1))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]


Save and Load Array

In [97]:
arr = np.array([1,0,0,8])
np.save('my_array.npy', arr)

In [98]:
loaded_arr = np.load('my_array.npy')
print(loaded_arr)


[1 0 0 8]
